account/urls.py
from django.urls import path
from .import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "account"
urlpatterns = [
    path('', views.ProfileView.as_view(), name="deatil"),
    path('login/', LoginView.as_view(template_name="main/login.html" , success_url="/"), name="login"),
    path('logout/', LogoutView.as_view(template_name="main/logout.html"), name="logout"),
    path("register/", views.register, name='register'),
    path("update/", views.ProfileUpdate.as_view(), name='update'),
]

book_store/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('1abdullajonov/', admin.site.urls),
    path("", include("main.urls", namespace='main')),
    path("account/", include("account.urls", namespace='account')),

    #medi root
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "main"
urlpatterns = [
    path('', views.homeView, name="index"),
    path('book-list/', views.BooksView, name="book-list"),
    path('mybooks/', views.MyBookView, name="my-book"),
    path("delete/<slug:url>/", views.delete_view, name='delete'),
    path('book-list/<slug:slug>', views.BookView, name="detail"),
    path('update/<slug:url>/', views.UpdateBook.as_view(), name="edit"),
    path("create_advert/", views.BookCreate.as_view(), name="create-book"),
    
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

class User(AbstractUser):
	GENDER = (
		('Ayol', 'Ayol'),
		('Erkak', 'Erkak'),
	)
	ADDRESS = (
		('Andijon', 'Andijon'),
		('Namangan', 'Namangan'),
		('Samarqand', 'Samarqand'),
		('Tashkent', 'Tashkent'),
		('Jizzax', 'Jizzax'),
		('Surxondaryo', 'Surxondaryo'),
		('Navoiy', 'Navoiy'),
		('Xorazm', 'Xorazm'),
		('Qashqadaryo', 'Qashqadaryo'),
		('Buxoro', 'Buxoro'),
		('Sirdaryo', 'Sirdaryo'),
		('Fargona', 'Fargona'),
	)
	
	name = models.CharField("Name", max_length=256)
	surname = models.CharField("Surname", max_length=256)
	username = models.CharField("Username", max_length=256, unique=True, null=True)
	age = models.PositiveIntegerField("Age", null=True)
	phone = models.CharField("Phone", max_length=18)
	avatar = models.ImageField("Image", upload_to="user-images/", null=True, blank=True, default='default.png')
	gender = models.CharField("Gender", max_length=128, choices=GENDER)
	address = models.CharField("Address", max_length=128, choices=ADDRESS)

	created_at = models.DateTimeField("Created at", auto_now_add=True)
	updated_at = models.DateTimeField("Updated_at", auto_now=True)

	USERNAME_FIELD = "username"
	first_name = None
	last_name = None

	def __str__(self):
		return f'{self.name} -- {self.username}'
 
	@property
	def avatar_url(self):
		return f"{settings.HOST}{self.avatar.url}" if self.avatar else ""

	class Meta:
		db_table = "user"
		verbose_name = "user"
		verbose_name_plural = "users"

main/models.py
from django.db import models
from django.conf import settings
from account.models import User
from main.slug import unique_slugify
import telebot
from telebot import types


TOKEN = '5447606124:AAH54uriHV3Ja_D_mlKOqf3Kf1cRCj86GdM'
bot = telebot.TeleBot(TOKEN)
# Create your models here.
class Genre(models.Model):
    title = models.CharField("Title", max_length=256)
    slug = models.SlugField("Slug", max_length=256, blank=True)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        db_table = "genre"
        verbose_name = "genre"
        verbose_name_plural = "genres"

class Book(models.Model):
    ADDRESS = (
		('Andijon', 'Andijon'),
		('Namangan', 'Namangan'),
		('Samarqand', 'Samarqand'),
		('Tashkent', 'Tashkent'),
		('Jizzax', 'Jizzax'),
		('Surxondaryo', 'Surxondaryo'),
		('Navoiy', 'Navoiy'),
		('Xorazm', 'Xorazm'),
		('Qashqadaryo', 'Qashqadaryo'),
		('Buxoro', 'Buxoro'),
		('Sirdaryo', 'Sirdaryo'),
		('Fargona', 'Fargona'),
	)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="books", default=None, null=True)
    slug = models.SlugField("Slug", max_length=256, blank=True, unique=True)	
    title = models.CharField("Title", max_length=256)
    author_pen = models.CharField("Book Author", max_length=100)
    location = models.CharField('loacation', max_length=256,  choices=ADDRESS)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name="books", default=None, null=True)
    description = models.TextField("Description", max_length=200)
    image = models.ImageField("Image", upload_to="book_images")
    created_at = models.DateTimeField("Created time", auto_now_add=True)
    likes_count = models.PositiveIntegerField("Likes", default=0)


    def __str__(self):
        return f"{self.title}"

    @property
    def image_url(self):
        return f"{settings.HOST}{self.image.url}" if self.image else ""
    def save(self,*args, **kwargs):
        try:
            this = Book.objects.select_related('author', 'genre').get(id=self.id)
            if this.image != self.image:
                this.image.delete()
            if this.title != self.title or this.author_pen != self.author_pen or this.genre != self.genre or this.description != self.description :
                self.is_checked = False
                self.is_ban = False
                bot.send_message(801531808, f'new \nhttps://bookswap.uz/book-list/{slug} \n https://bookswap.uz/admin') 

        except: pass
        
        slug = '%s' % (self.title)
        unique_slugify(self, slug)

        if self.is_checked:
            img = 'https://bookswap.uz/media/book_images/{self.image}'
            text = f'<b>Nomi</b>: {self.title} \n<b>Muallifi</b>: {self.author_pen} \n<b>Janri</b>: {self.genre}\n<b>kitob haqida:</b> {self.description} \n\n <a href="https://bookswap.uz/book-list/{slug}">Batafsil</a> \n\n Bookswap.uz | t.me/bookswapuz'
            bot.send_photo(chat_id='@bookswapuz', photo = img, caption=text, parse_mode='HTML') 
        
        super(Book, self).save(*args, **kwargs)
            

    def delete(self, *args, **kwargs):
        storage, path = self.image.storage, self.image.path
        super(Book, self).delete(*args, **kwargs)
        storage.delete(path)


    class Meta:
        ordering = ['-id']
        db_table = "book"
        unique_together = ["slug"]
        verbose_name = "book"
        verbose_name_plural = "books"

main/forms.py
from email.headerregistry import Address
from django import forms
from .models import Book
from account.models import User

class StockSearchForm(forms.ModelForm):
    query = forms.CharField()
    query.widget.attrs.update({'placeholder': 'qidiruv',})
    class Meta:
        model = Book
        fields = ['genre','location']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from .models import *
from account.models import User
from .forms import *


# prefetch_related('user_liked') Many to many feld uchun

def homeView(request):
    return render(request, "main/index.html",)

def BooksView(request):
    form = StockSearchForm(request.POST or None)
    queryset = Book.objects.select_related('genre', 'author').all()
    #Searching an item and category
    if request.method == 'POST':
        if form['genre'].value():
            queryset = queryset.filter(genre=form['genre'].value())
        if form['location'].value():
            queryset = queryset.select_related('genre', 'author').filter(location=form['location'].value())
        if form['query'].value():
            queryset = queryset.select_related('genre', 'author').filter(title__icontains=form['query'].value())    
                
    paginator = Paginator(queryset, 12)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "form": form,
        "object_list": page_obj,
    }

    return render(request, "advert/book_list.html", context)


@login_required(login_url='/account/login/')
def MyBookView(request):
    author_book = Book.objects.select_related('genre', 'author').filter(author= request.user)
    return render(request, 'advert/my_advert.html', {"object": author_book})

def delete_view(request, url):
    obj = get_object_or_404(Book, slug = url)
    if obj.author != request.user:
        return HttpResponseServerError()
    else:
        context ={'object': obj}
        if request.method =="POST":
            obj.delete()
            return HttpResponseRedirect("/mybooks")
 
    return render(request, "advert/confirm.html", context)


class UpdateBook(LoginRequiredMixin, UpdateView):
    model = Book
    template_name = 'advert/update_advert.html'
    fields = ("title", "author_pen", "genre", "description", "image")
    success_url = '/mybooks/'
    slug_field = 'slug'
    slug_url_kwarg = 'url'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            return HttpResponseServerError()
        return super(UpdateBook, self).dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = Book.objects.select_related('author', 'genre').filter(author=self.request.user)
        context["books"] = book
        return context

    
def BookView(request, slug):
    book = Book.objects.select_related('genre', 'author').get(slug=slug)
    author_books = Book.objects.select_related('genre', 'author').exclude(slug = slug).filter(is_checked = True, author = book.author)[:16]
    related_books = Book.objects.select_related('genre', 'author').exclude(slug = slug).filter(is_checked = True, genre=book.genre)[:16]
    if book.is_checked == True or request.user.is_staff or book.author == request.user:
        context = {
            "object": book,
            "books": related_books,
            "author_books": author_books
        }
    return render(request, "advert/detail.html", context)

class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    template_name = 'advert/create_advert.html'
    fields = ("title", "author_pen", "genre", "description", "image")
    success_url = '/mybooks/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = Book.objects.select_related('author', 'genre').filter(author=self.request.user)
        context["books"] = book
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.location = self.request.user.address
        form.instance.is_checked = False
        form.instance.is_ban = False
        return super().form_valid(form)
    

templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Google Tag Manager -->
  <script>(function (w, d, s, l, i) {
      w[l] = w[l] || []; w[l].push({
        'gtm.start':
          new Date().getTime(), event: 'gtm.js'
      }); var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
          'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-WCJ8MMM');</script>
  <!-- End Google Tag Manager -->
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block meta %}
  {% endblock meta %}

  <link rel="shortcut icon" href="/static/img/logo.png" type="image/png">
  <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.1.1/css/all.css">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
  <link rel="stylesheet" href="/static/css/style.css">
  <title>Book swap</title>
</head>

<body>
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WCJ8MMM" height="0" width="0"
      style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  <nav class="nav" id="navbar">
    <div class="logo">
      <a href="/" class="text-light text-decoration-none">
        <img src="/static/img/logo.png" alt="">
        <span>Book swap</span>
      </a>
    </div>
    <ul class="nav-items">
      <li>
        <a href="/">Bosh sahifa</a>
      </li>
      <li>
        <a href="{% url 'main:book-list' %}">E’lonlar oynasi</a>
      </li>
      <li>
        <a href="{% url 'main:my-book' %}">Mening e’lonlarim</a>
      </li>
      <li>
        <a href="{% url 'main:create-book' %}">Kitob joylash</a>
      </li>
    </ul>
    <div class="menu-bar">
      {% if request.user.is_authenticated %}
      <a href="{% url 'main:book-list' %}" class="text-light text-decoration-none">
        <i class="fa-light fa-search"></i>
      </a>
      <a href="{% url 'account:deatil' %}" class="text-light"><i class="fa-light fa-user"></i></a>
      <i class="fa-light event-btn"></i>
      <!-- <i class="fa-solid fa-x"></i> -->
      {% else %}
      <a href="{% url 'account:login' %}" class="text-light"><i class="fa-solid fa-right-to-bracket"></i></a>
      {% endif %}
    </div>

  </nav>
  {% block content %}
  {% endblock content %}

  <script type="text/javascript" src="/static/js/jquery.js"></script>
  <script type="text/javascript" src="/static/js/script.js"></script>

  {% block code %}
  {% endblock code %}
</body>

</html>

templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
  <main>
    <div class="row">
      <div class="col-lg-6 mt-2">
        <div class="box row">
          <div class="col-xl-7 col-lg-8 col-md-7 col-sm-6 col-8  content">
            <br>
            <h1>E’lon ko‘rish</h1>
            <p>Siz bu sayt orqali o’zingizda bor kitobni manfaatli ravishda siz qidirgan yoki o‘zingizga yoqqan kitobga
              alishtirishingiz mumkin.
            </p>
            <p>
              Ro‘yxatdan o‘ting va ozingizdagi kitoblarni akkauntingizga joylang.
            </p>
            <br>
            <a href="{% url 'main:book-list' %}" class="book-btn">
              E'lon ko‘rish
            </a>
          </div>
          <div class="col-xl-5 col-lg-3 col-md-5 col-sm-6 col-4">
            <img src="/static/img/Book.png" alt="" class="img-fluid">
          </div>
          <br>
          <br><br>
        </div>
      </div>
      <div class="col-lg-6 mt-2">
        <div class="box row">
          <div class="col-xl-7 col-lg-8 col-md-7 col-sm-8 col-8  content">
            <br>
            <h1>E’lon joylash</h1>
            <p>Siz bu sayt orqali o’zingizda bor kitobni manfaatli ravishda siz qidirgan yoki o‘zingizga yoqqan kitobga
              alishtirishingiz mumkin.
            </p>
            <p>
              Ro‘yxatdan o‘ting va ozingizdagi kitoblarni akkauntingizga joylang.
            </p>
            <br>
            {% if request.user.is_authenticated %}
            <a href="{% url 'main:create-book' %}" class="book-btn">
              E'lon Joylash
            </a>
            {% else %}
            <a href="{% url 'account:login' %}" class="book-btn">
              E'lon Joylash
            </a>
            {% endif %}
          </div>
          <div class="col-xl-5 col-lg-3 col-md-5 col-sm-4 col-4">
            <img src="/static/img/Book2.png" alt="" class="img-fluid">
          </div>
          <br>
          <br><br>
        </div>
      </div>
    </div>
  </main>

{% endblock %}
{% block meta %}
<meta name="description" content="Bookswap.uz O'zingiz hohlagan kitob qidiring va soting"/>
<meta name="keywords" content="Bookswap.uz bookswap kitob magazin onlayn kitob magazin kitob dokoni">
{% endblock meta %}

templates/main/login.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
<main class="login">
    <div class="form container">
        <h1>Kirish</h1>
        <br><br>
        <form action="" method="post">
            {% csrf_token %}
            <div class="input-block">
                <i class="fa-light fa-user"></i>
                <!-- {{ form.username }} -->
                <input type="text" name="username" placeholder="Foydalanuvchi nomi" name="username" autocomplete="off"
                    autofocus="" autocapitalize="none"  maxlength="256" required=""  id="id_username">
                {% if form.errors %}
                <i class="fa-solid fa-triangle-exclamation text-danger"></i>
                {% endif %}
            </div>
            <br><br>
            <div class="input-block">
                <i class="fa-light fa-lock"></i>
                <input type="password" name="password" required="" id="id_password" autocomplete="off" placeholder="Parol">
                {% if form.errors %}
                <i class="fa-solid fa-triangle-exclamation text-danger"></i>
                {% endif %}
                <!-- <input type="password" placeholder="password" name="password" autocomplete="off"> -->
            </div>
            <br><br>
            <input type="submit" value="Kirsh" class="btn btn-submit">
            <br><br><br>
            <h5>Akkauntingiz yo’qmi ? <a href="{% url 'account:register'%}">Ro’yxatdan o’ting</a> </h5>
        </form>
    </div>
</main>
<style>
    html{
      height: 100vh !important;
      overflow: auto !important;
    }
    body{
      height: 100vh;
      overflow: auto;
    }
    </style>
{% endblock %}

templates/main/logout.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
<main class="login">
    <div class="form container" style="min-height: 350px; display: flex;  flex-direction: column;  justify-content: space-evenly;">
        <h1>Hisobdan chiqildi</h1>
        <br><br>
        <h5><a href="{% url 'account:login'%}" class="h3">Qayta kiring</a> <span class="h4">yoki </span> <a href="{% url 'account:register'%}" class="h3">Ro’yxatdan o’ting</a></h5>

    </div>
</main>
<style>
    html{
      height: 100vh !important;
      overflow: auto !important;
    }
    body{
      height: 100vh;
      overflow: auto;
    }
    </style>
{% endblock %}

templates/main/profile.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
<main class="login">
  <div class="profile">
    <div class="text-center img_text">
      <img src="{{object.avatar.url}}" width="120px" height="120px"
        style="border-radius: 50%; height: 120px; width: 120px;" alt="persons-image">
    </div>
    <ul>
      <li>
        <strong>Ism:</strong>
        <span>{{object.name}}</span>
      </li>
      <li>
        <strong>Familiya:</strong>
        <span>{{object.surname}}</span>
      </li>
      <li>
        <strong>Foydalanuvchi nomi:</strong> 
        <span>@{{object.username}}</span>
      </li>
      <li>
        <strong>Yashash joyi:</strong>
        <span>{{object.address}}</span>
      </li>
      <li>
        <strong>Telefon raqamai:</strong>
        <span>{{object.phone}}</span>
      </li>
    </ul>
    <div class="change-button">
      <a href="{% url 'account:update' %}" class="btn btn-submit">O‘zgartirish</a>
      <a href="{% url 'account:logout' %}" class="btn btn-submit">Hisobdan chiqish</a>
    </div>
  </div>
</main>
<style>
  html{
    height: 100vh !important;
    overflow: auto !important;
  }
  body{
    height: 100vh;
    overflow: auto;
  }
  </style>
{% endblock content %}

templates/main/register.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
<main class="login">
    <div class="form container mt-3">
        <h1>Register</h1>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="input-block">
                <i class="fa-solid fa-user-check"></i>
                {{ form.username }}
                {% if form.username.errors %}
                <i class="fa-solid fa-triangle-exclamation text-danger"></i>
                {% endif %}
            </div>
            <div class="input-block">
                <i class="fa-light fa-user"></i>
                {{ form.name }}
                {% if form.name.errors %}
                <i class="fa-solid fa-triangle-exclamation text-danger"></i>
                {% endif %}
            </div>
            <div class="input-block">
                <i class="fa-solid fa-user-hair"></i>
                {{ form.surname }}
                {% if form.surname.errors %}
                <i class="fa-solid fa-triangle-exclamation text-danger"></i>
                {% endif %}
            </div>
            <div class="input-block">
                <i class="fa-solid fa-chart-waterfall"></i>
                {{ form.age }}
                {% if form.age.errors %}
                <i class="fa-solid fa-triangle-exclamation text-danger"></i>
                {% endif %}
            </div>
            <div class="input-block">
                <i class="fa-solid fa-phone">+998</i>
                {{ form.phone }}
                {% if form.phone.errors %}
                <i class="fa-solid fa-triangle-exclamation text-danger"></i>
                {% endif %}
            </div>
            <div class="input-block">
                <i class="fa-solid fa-genderless"></i>
                {{ form.gender }}
            </div>
            <div class="input-block">
                <i class="fa-solid fa-location-dot"></i>
                {{ form.address }}
            </div>
            <div class="input-block">
                <i class="fa-light fa-lock"></i>
                {{ form.password }}
                {% if form.password.errors %}
                <i class="fa-solid fa-triangle-exclamation text-danger"></i>
                {% endif %}
            </div>
            <div class="input-block">
                <i class="fa-solid fa-hashtag-lock"></i>
                {{ form.repeat_password }}
                {% if form.repeat_password.errors %}
                <i class="fa-solid fa-triangle-exclamation text-danger"></i>
                {% endif %}
            </div>
            
            
            <input type="submit" value="Kirsh" class="btn btn-submit">
            <br><br>
        </form>
    </div>
</main>
{% endblock %}
{% block code %}
<script type="text/javascript" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/jquery.inputmask.bundle.js"></script>
<script>
    $("#id_phone").inputmask({ mask: "(99) 999 99 99" });
</script>
{% endblock %}

templates/main/update_profile.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
<main class="login">
    <div class="form">
      <div class="text-center img_text">
          <img src="{{request.user.avatar.url}}" width="120px" height="120px" style="border-radius: 50%; height: 120px; width: 120px;" alt="persons-image" id="profileImg">
      </div>
      <form form method="post" enctype="multipart/form-data">
        {% csrf_token %}
          <input type="file" name="avatar" accept="image/*" id="id_avatar" style="display: none;">
          <label for="id_avatar">
              <h3>Profile rasmini O‘zgartirish</h3>
          </label>
          <div class="input-block">
            <i class="fa-solid fa-user-check"></i>
            {{ form.username }}
            {% if form.username.errors %}
            <i class="fa-solid fa-triangle-exclamation text-danger"></i>
            {% endif %}
        </div>
        <div class="input-block">
            <i class="fa-light fa-user"></i>
            {{ form.name }}
            {% if form.name.errors %}
            <i class="fa-solid fa-triangle-exclamation text-danger"></i>
            {% endif %}
        </div>
        <div class="input-block">
            <i class="fa-solid fa-user-hair"></i>
            {{ form.surname }}
            {% if form.surname.errors %}
            <i class="fa-solid fa-triangle-exclamation text-danger"></i>
            {% endif %}
        </div>
        <div class="input-block">
            <i class="fa-solid fa-chart-waterfall"></i>
            {{ form.age }}
            {% if form.age.errors %}
            <i class="fa-solid fa-triangle-exclamation text-danger"></i>
            {% endif %}
        </div>
        <div class="input-block">
          <i class="fa-solid fa-phone">+998</i>
            {{ form.phone }}
            {% if form.phone.errors %}
            <i class="fa-solid fa-triangle-exclamation text-danger"></i>
            {% endif %}
        </div>
        <div class="input-block">
            <i class="fa-solid fa-location-dot"></i>
            {{ form.address }}
        </div>
        <br>
          <input type="submit" value="O‘zgartirish" class="btn btn-submit">
          <br><br>
      </form>
    </div>
</main>
<style>
  html{
    height: 100vh !important;
    overflow: auto !important;
  }
  body{
    height: 100vh;
    overflow: auto;
  }
  </style>
{% endblock %}

{% block code %}
<script type="text/javascript" src="/static/js/resizer_image.js"></script>
<script type="text/javascript" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/jquery.inputmask.bundle.js"></script>
<script>
  $("#id_phone").inputmask({ mask: "(99) 999 99 99" });
    let avatar_input = document.querySelector('#id_avatar');
    var target = document.getElementById('profileImg')
    let input = document.querySelectorAll('input');
    let value = ['foydalanuvchi nomi', 'Ismingiz', 'Familangiz', 'yoshingiz', ' nomeringiz', ]
    for (var i = 2; i < input.length-1; i++) {
        input[i].setAttribute('autocomplete', 'off')
        input[i].setAttribute('placeholder', value[i-2])
    }
    let file;

    avatar_input.addEventListener("change", (event)=>{
      event.preventDefault();
      file = event.target.files[0]
      showFile();
    });

    function showFile(){
      let fileType = file.type;
      let validExtensions = ["image/jpeg", "image/jpg", "image/png"];
      if(validExtensions.includes(fileType)){
        let fileReader = new FileReader();
        fileReader.onload = ()=>{
          let fileURL = fileReader.result;
          target.attributes.src.nodeValue = `${fileURL}`
        }
        fileReader.readAsDataURL(file);
      }else{
        alert("This is not an Image File!");
      }
    }
  $('#id_avatar').imageUploadResizer({
      max_width: 280, // Defaults 1000
      max_height: 280, // Defaults 1000
      quality: 1, // Defaults 1
      do_not_resize: ['gif', 'svg'], // Defaults []
  });
</script>
{% endblock %}