account/urls.py
from django.urls import path
from .import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "account"
urlpatterns = [
    path('', views.ProfileView.as_view(), name="deatil"),
    path('login/', LoginView.as_view(template_name="main/login.html" , success_url="/"), name="login"),
    path('logout/', LogoutView.as_view(template_name="main/logout.html"), name="logout"),
    path("register/", views.register, name='register'),
    path("update/", views.ProfileUpdate.as_view(), name='update'),
]

book_store/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('1abdullajonov/', admin.site.urls),
    path("", include("main.urls", namespace='main')),
    path("account/", include("account.urls", namespace='account')),

    #medi root
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "main"
urlpatterns = [
    path('', views.homeView, name="index"),
    path('book-list/', views.BooksView, name="book-list"),
    path('mybooks/', views.MyBookView, name="my-book"),
    path("delete/<slug:url>/", views.delete_view, name='delete'),
    path('book-list/<slug:slug>', views.BookView, name="detail"),
    path('update/<slug:url>/', views.UpdateBook.as_view(), name="edit"),
    path("create_advert/", views.BookCreate.as_view(), name="create-book"),
    
]

main/models.py
from django.db import models
from django.conf import settings
from account.models import User
from main.slug import unique_slugify
import telebot
from telebot import types


TOKEN = '5447606124:AAH54uriHV3Ja_D_mlKOqf3Kf1cRCj86GdM'
bot = telebot.TeleBot(TOKEN)
# Create your models here.
class Genre(models.Model):
    title = models.CharField("Title", max_length=256)
    slug = models.SlugField("Slug", max_length=256, blank=True)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        db_table = "genre"
        verbose_name = "genre"
        verbose_name_plural = "genres"

class Book(models.Model):
    ADDRESS = (
		('Andijon', 'Andijon'),
		('Namangan', 'Namangan'),
		('Samarqand', 'Samarqand'),
		('Tashkent', 'Tashkent'),
		('Jizzax', 'Jizzax'),
		('Surxondaryo', 'Surxondaryo'),
		('Navoiy', 'Navoiy'),
		('Xorazm', 'Xorazm'),
		('Qashqadaryo', 'Qashqadaryo'),
		('Buxoro', 'Buxoro'),
		('Sirdaryo', 'Sirdaryo'),
		('Fargona', 'Fargona'),
	)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="books", default=None, null=True)
    slug = models.SlugField("Slug", max_length=256, blank=True, unique=True)	
    title = models.CharField("Title", max_length=256)
    author_pen = models.CharField("Book Author", max_length=100)
    location = models.CharField('loacation', max_length=256,  choices=ADDRESS)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name="books", default=None, null=True)
    description = models.TextField("Description", max_length=200)
    image = models.ImageField("Image", upload_to="book_images")
    created_at = models.DateTimeField("Created time", auto_now_add=True)
    likes_count = models.PositiveIntegerField("Likes", default=0)


    def __str__(self):
        return f"{self.title}"

    @property
    def image_url(self):
        return f"{settings.HOST}{self.image.url}" if self.image else ""
    def save(self,*args, **kwargs):
        try:
            this = Book.objects.select_related('author', 'genre').get(id=self.id)
            if this.image != self.image:
                this.image.delete()
            if this.title != self.title or this.author_pen != self.author_pen or this.genre != self.genre or this.description != self.description :
                self.is_checked = False
                self.is_ban = False
                bot.send_message(801531808, f'new \nhttps://bookswap.uz/book-list/{slug} \n https://bookswap.uz/admin') 

        except: pass
        
        slug = '%s' % (self.title)
        unique_slugify(self, slug)

        if self.is_checked:
            img = 'https://bookswap.uz/media/book_images/{self.image}'
            text = f'<b>Nomi</b>: {self.title} \n<b>Muallifi</b>: {self.author_pen} \n<b>Janri</b>: {self.genre}\n<b>kitob haqida:</b> {self.description} \n\n <a href="https://bookswap.uz/book-list/{slug}">Batafsil</a> \n\n Bookswap.uz | t.me/bookswapuz'
            bot.send_photo(chat_id='@bookswapuz', photo = img, caption=text, parse_mode='HTML') 
        
        super(Book, self).save(*args, **kwargs)
            

    def delete(self, *args, **kwargs):
        storage, path = self.image.storage, self.image.path
        super(Book, self).delete(*args, **kwargs)
        storage.delete(path)


    class Meta:
        ordering = ['-id']
        db_table = "book"
        unique_together = ["slug"]
        verbose_name = "book"
        verbose_name_plural = "books"

templates/advert/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Google Tag Manager -->
  <script>(function (w, d, s, l, i) {
      w[l] = w[l] || []; w[l].push({
        'gtm.start':
          new Date().getTime(), event: 'gtm.js'
      }); var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
          'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-WCJ8MMM');</script>
  <!-- End Google Tag Manager -->
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="/static/img/logo.png" type="image/png">
  {% block meta %}

  {% endblock meta %}

  <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.1.1/css/all.css">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
  <link rel="stylesheet" href="/static/css/style.css">
  <title>Book swap</title>
</head>

<body class="page">
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WCJ8MMM" height="0" width="0"
      style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  <nav class="nav nav-advert" id="navbar">
    <div class="logo">
      <a href="/" class="text-dark text-decoration-none">
        <img src="/static/img/logo.png" alt="">
        <span>Book swap</span>
      </a>
    </div>
    <ul class="nav-items">
      <li>
        <a href="/">Bosh sahifa</a>
      </li>
      <li>
        <a href="{% url 'main:book-list' %}">E’lonlar oynasi</a>
      </li>
      <li>
        <a href="{% url 'main:my-book' %}">Mening e’lonlarim</a>
      </li>
      <li>
        <a href="{% url 'main:create-book' %}">Kitob joylash</a>
      </li>
    </ul>
    <div class="menu-bar">
      {% if request.user.is_authenticated %}
      <a href="{% url 'main:book-list' %}" class="text-dark text-decoration-none">
        <i class="fa-light fa-search"></i>
      </a>
      <a href="{% url 'account:deatil' %}" class="text-dark"><i class="fa-light fa-user"></i></a>
      <i class="fa-light event-btn"></i>
      <!-- <i class="fa-solid fa-x"></i> -->
      {% else %}
      <a href="{% url 'account:login' %}" class="text-dark"><i class="fa-solid fa-right-to-bracket"></i></a>
      {% endif %}
    </div>

  </nav>
  {% block content %}

  {% endblock %}

  <footer>
    <div class="row">
      <div class="col-lg-3">
        <img src="/static/img/logo.png" alt="" width="33px">
        <span class="brend-name">Book swap</span>
        <br><br>
        <h5>
          Kitobingiz sizga foyda keltirishini hohlasangiz, uni boshqalar bilan bo‘lishing !
        </h5>
      </div>
      <div class="col-lg-2">
        <ul>
          <li>
            <a href="/">Bosh sahifa</a>
          </li>
          <li>
            <a href="{% url 'main:book-list' %}">E’lonlar oynasi</a>
          </li>
          <li>
            <a href="{% url 'main:my-book' %}">Mening e’lonlarim</a>
          </li>
          <li>
            <a href="{% url 'main:create-book'%}">Kitob joylash</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-3">
        <p>Kitob joylash haqida ma’lumot</p>
        <p>Accaunt ochish haqida ma’lumot</p>
        <p>Ma’lumotlar</p>

      </div>
      <div class="col-lg-4">
        <form method="post" id="header-search-desktop-span" onchange="submit()" action="{% url 'main:book-list' %}">
          {% csrf_token %}
          <div class="input-group">
            <i class="fas fa-search"></i>
            <input type="text" name="query" placeholder="qidiruv">
          </div>
        </form>
      </div>
    </div>
    <br>
    <hr>
    <center>
      <h4>@Book swap 2022</h4>
    </center>
  </footer>

  <script  type="text/javascript" src="/static/js/jquery.js"></script>
  <script  type="text/javascript" src="/static/js/owl.carousel.min.js"></script>
  <script  type="text/javascript" src="/static/js/script.js"></script>

  {% block code %}
  {% endblock code %}
</body>

</html>

templates/advert/book_list.html
{% extends "advert/base.html" %}
{% load static %}
{% block content %}
<header>
  <h1>E’lonlar oynasi</h1>
  <form method="post" id="header-search-desktop-span" onchange="submit()">
    {% csrf_token %}
    <div class="search">
      <div class="big-input">
        <i class="fa-light fa-search"></i>
        {{form.query}}
      </div>
      <div class="selection-group">
        <div class="select-input">
          <i class="fal fa-location-dot"></i>
          {{form.location}}
        </div>
        <div class="select-input">
          <i class="fal fa-book-open"></i>
          {{form.genre}}
        </div>
      </div>
    </div>
  </form>
</header>
<div class="container">
  <div class="advert-section mt-5">
    <div class="row">
      
      {% for book in object_list %}
      <div class="col-6 col-sm-6 col-md-4 col-lg-3">
        <a href="{% url 'main:detail' book.slug %}" class="text-dark" style="text-decoration: none;">
          <div class="advert-box">
            <img src="{{book.image.url}}" alt="">
            <ul>
              <li>
                <strong>Nomi:</strong>
                <span>{{book.title}}</span>
              </li>
              <li>
                <strong>Avtori:</strong>
                <span>{{book.author_pen}}</span>
              </li>
              <li>
                <strong>Janri:</strong>
                <span>{{book.genre}}</span>
              </li>
            </ul>
            <span class="about-box">{{book.author.address}} <br> {{book.created_at}}</span>
          </div>
        </a>
      </div>
      {% empty %}
      <h1 class="m-5">Hech narsa topilmadi</h1>
      {% endfor %}

  

    </div>
  </div>

  <div class="paginator ">

    {% if object_list.has_previous %}
    <a href="?page={{ object_list.previous_page_number }}"><i class="fas fa-chevron-left"></i></a>
    {% endif %}
    <ul>
      {% if object_list > 1 %}
        {% for i in object_list.paginator.page_range %}
          {% if object_list.number == i %}
          <li class=current><a href="" disabled>{{ i }}</a ></li>
          {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
          {% endfor %}
      {% endif %}
      
    </ul>

    {% if object_list.has_next %}
    <a href='?page={{ object_list.next_page_number }}'><i class="fas fa-chevron-right"></i></a>
    {% endif %}
  </div>
</div>

{% endblock %}

templates/advert/confirm.html
{% extends "advert/base.html" %}
{% load static %}
{% block content %}
<header>
    <section class="add_advert">
        <h1>E’lon Joylash</h1>
        <div class="row">
            <div class="col-lg-4 order-lg-2">
                <div class="white-card" style="display: flex;  align-items: center;  justify-content: center; flex-direction:column;">
                    <h1 class="text-danger">Rostan ham ushbu postni o'chirib yubormoqchimisiz</h1>
                    <br><br>
                    <form method="post">
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn" type="submit" style="max-width: 180px;"> ha</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-8 col-lg-fisrt">
                <div class="white-card">
                    <div class="row">
                        <div class="col-sm-5">
                            <img src="{{object.image.url}}" alt="" style="max-height: 400px; max-width: 100%;">
                        </div>
                        <div class="col-sm-7">
                            <ul class="about-book" style="text-transform:capitalize;">
                                <li>
                                    <strong>Nomi:</strong>
                                    <span>{{object.title}}</span>
                                </li>
                                <li>
                                    <strong>Avtori:</strong>
                                    <span>{{object.author_pen}}</span>
                                </li>
                                <li>
                                    <strong>Janri:</strong>
                                    <span>{{object.genre}}</span>
                                </li>
                                <li>
                                    <strong>Kitob haqida:</strong>
                                    <br>
                                    <p>{{object.description}}</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <br><br>
</header>
{% endblock %}

templates/advert/create_advert.html
{% extends "advert/base.html" %}
{% load static %}
{% block content %}
<header>
    <section class="add_advert">
        <h1>E’lon Joylash</h1>
        <div class="row">
            <div class="col-lg-7">
                <div class="white-card">
                    <form method="post" enctype="multipart/form-data" class="row">
                        <div class="col-sm-6">
                            {% csrf_token %}
                            <input type="file" name="image" accept="image/*" required="" id="id_image"
                                class="value-input" placeholder="" style="display: none;">
                            <label for="id_image">
                                <img src="/static/img/select_img.png" alt="image" id="uploadImg"
                                    style="max-height: 400px; width: 100%;">
                            </label>
                        </div>
                        <div class="col-sm-6">
                            <div class="input-group">
                                {{ form.title }}
                                {{ form.author_pen }}

                                {{ form.genre }}
                                {{ form.description }}
                                <br class="">
                                <button class="btn" type="submit">
                                    Qabul qilish
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="white-card">
                    <div class="about-user">
                        <h2 class="mr-3">Foydalanuvchi</h2>
                        <div class="user-componet">
                            <img src="{{request.user.avatar.url}}" alt="">
                            <div class="user-bio">
                                <h3 style="text-transform: capitalize;">{{request.user.name}} {{request.user.surname}}
                                </h3>
                                <h5>Last seen: {{request.user.updated_at }}</h5>
                            </div>
                        </div>
                        <ul>
                            <li>
                                <strong>Foydalanuvchi nomi:</strong>
                                <span>@{{request.user.username }}</span>
                            </li>
                            <li>
                                <strong>Joylashuv:</strong>
                                <span>{{request.user.address}} Shaxri</span>
                            </li>
                            <li>
                                <strong>Telefon raqimi:</strong>
                                <span>{{request.user.phone}}</span>
                            </li>
                        </ul>
                        <br>
                        <a href="tel: {{request.user.phone}}" class="text-light">
                            <button class="btn">
                                Qong'iroq
                            </button>

                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <br><br>
</header>
<div class="container">
    <section class="advert-section mt-5">
      {% if books %}
      <h1>Sizning barcha e’lonlari:</h1>
      {% endif %}
      <div class="owl-carousel owl-theme">
        {% for book in books%}
        <div class="item d-inline">
          <a href="{% url 'main:detail' book.slug %}" class="text-dark" style="text-decoration: none;">
            <div class="advert-box">
              <img src="{{book.image.url}}" alt="">
              <ul>
                <li>
                  <strong>Nomi:</strong>
                  <span>{{book.title}}</span>
                </li>
                <li>
                  <strong>Avtori:</strong>
                  <span>{{book.author_pen}}</span>
                </li>
                <li>
                  <strong>Janri:</strong>
                  <span>{{book.genre}}</span>
                </li>
              </ul>
              <span class="about-box">{{book.author.address}} <br> {{book.created_at}}</span>
            </div>
          </a>
        </div>
        {% endfor %}
      </div>
    </section>
    <br><br>
  </div>
<style>
    .center{
        margin: 120px 10% 0 10%;
    }
</style>
{% endblock %}

{% block code %}
<script type="text/javascript" src="/static/js/resizer_image.js"></script>
<script>
    let input = document.querySelectorAll('input');
    for (var i = 0; i < input.length-1; i++) {
        arr = ['', '', 'Sarlavha', 'Muallif', 'qidiruv']
        input[i].classList.add('value-input')
        input[i].setAttribute('placeholder', `${arr[i]}`)
        input[i].setAttribute( 'autocomplete',"off")
    }
    let textArea = document.querySelectorAll('textarea')[0];
    textArea.classList.add('value-input');
    textArea.setAttribute('placeholder', 'Qoshimcha xabar');
    textArea.attributes['cols'].nodeValue = "12";
    textArea.attributes['rows'].nodeValue = "4";
    let input_file = document.querySelector('#id_image');
    input_file.style = 'display: none;'
    let target = document.querySelector('#uploadImg')
    let file;

    input_file.addEventListener("change", (event) => {
        event.preventDefault();
        file = event.target.files[0]
        showFile();
    });

    function showFile() {
        let fileType = file.type;
        let validExtensions = ["image/jpeg", "image/jpg", "image/png"];
        if (validExtensions.includes(fileType)) {
            let fileReader = new FileReader();
            fileReader.onload = () => {
                let fileURL = fileReader.result;
                target.attributes.src.nodeValue = `${fileURL}`
            }
            fileReader.readAsDataURL(file);
        } else {
            alert("This is not an Image File!");
        }
    }

$('#id_image').imageUploadResizer({
    max_width: 360, 
    max_height: 360, 
    quality: 1, 
    do_not_resize: ['gif', 'svg'],
});

$(".owl-carousel").owlCarousel({
  loop: false,
  margin: 10,
  dots: false,
  nav: false,

  responsive: {
    0: {
      items: 2
    },
    768: {
      items: 3
    },
    1336: {
      item: 4
    },
    1340: {
      items: 4
    }
  }
})
</script>
{% endblock %}

templates/advert/my_advert.html
{% extends "advert/base.html" %}
{% load static %}
{% block content %}
  <header>
    <section>
      <h1>Mening E’lonlarim</h1>
      <div class="edit-section mt-5">
          <div class="row">
              {% for  book in  object %}
              <div class="col-lg-4 col-xl-3 col-md-6 col-sm-6 col-12">
                  <div class="card">
                      <a href="{% url 'main:detail' book.slug%}" style="text-decoration: none;" class="text-dark">
                        <img src="{{ book.image.url}}" alt="" style="    width: 100%;  max-height: 300px;">
                    </a>
                    <div class="row">
                        <div class="col-10">
                          <ul>
                              <li>
                                  <strong>Nomi:</strong>
                                  <span>{{ book.title}}</span>
                              </li>
                              <li>
                                  <strong>Avtori:</strong>
                                  <span>{{ book.author_pen}}</span>
                              </li>
                              <li>
                                  <strong>Janri:</strong>
                                  <span>{{ book.genre}}</span>
                              </li>
                          </ul>
                          <span class="fa-solid fa-check">&nbsp &nbsp Sotuvga qoyildi</span>
                          <br>
                          <span class="about-box">{{book.author.address}} <br> {{book.created_at}}</span>
                      </div>
                      <div class="col-2">
                          <i class="fa-solid fa-ellipsis-vertical dropdown-button p-1 btn"></i>
                          <div class="dropdown">
                              <ul>
                                  <li>
                                      <a href="{% url 'main:edit' book.slug %}" class="text-dark" style="text-decoration: none;">
                                        Tahrirlash
                                    </a>
                                  </li>
                                  <li>
                                      <a href="{% url 'main:delete' book.slug %}" class="text-dark" style="text-decoration: none;">O'chirish</a>
                                  </li>
                              </ul>
                          </div>
                      </div>
                  </div>
                  </div>
              </div>
             {% endfor %}
          </div>
      </div>
      </div>
  </section>
    <center>
      <a href="{% url 'main:create-book' %}" class="btn btn-orange mt-5 mb-5">Kitob joylash</a>
    </center>
  </header>

  {% endblock %}

templates/advert/update_advert.html
{% extends "advert/base.html" %}
{% load static %}
{% block content %}
<header>
    <section class="add_advert">
        <h1>E’lon Tahrirlash</h1>
        <div class="row">
            <div class="col-lg-7">
                <div class="white-card">
                    <form method="post" enctype="multipart/form-data" class="row">
                        <div class="col-sm-6">
                            {% csrf_token %}
                            <div class="d-none">{{ form.image }}</div>
                            <label for="id_image">
                                <img src="{{ object.image.url }}" alt="image" id="uploadImg"
                                    style="max-height: 400px; width: 100%;">
                            </label>
                        </div>
                        <div class="col-sm-6">
                            <div class="input-group">
                                {{ form.title }}
                                {{ form.author_pen }}

                                {{ form.genre }}
                                {{ form.description }}
                                <br class="">
                                <button class="btn" type="submit">
                                    Qabul qilish
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="white-card">
                    <div class="about-user">
                        <h2 class="mr-3">Foydalanuvchi</h2>
                        <div class="user-componet">
                            <img src="{{request.user.avatar.url}}" alt="">
                            <div class="user-bio">
                                <h3 style="text-transform: capitalize;">{{request.user.name}} {{request.user.surname}}
                                </h3>
                                <h5>Last seen: {{request.user.updated_at }}</h5>
                            </div>
                        </div>
                        <ul>
                            <li>
                                <strong>Foydalanuvchi nomi:</strong>
                                <span>@{{request.user.username }}</span>
                            </li>
                            <li>
                                <strong>Joylashuv:</strong>
                                <span>{{request.user.address}} Shaxri</span>
                            </li>
                            <li>
                                <strong>Telefon raqimi:</strong>
                                <span>{{request.user.phone}}</span>
                            </li>
                        </ul>
                        <br>
                        <a href="tel:{{request.user.phone}}" class="text-light">
                            <button class="btn">
                                Qong'iroq
                            </button>

                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <br><br>
</header>
<div class="container">
    <section class="advert-section mt-5">
      {% if books %}
      <h1>Sizning barcha e’lonlari:</h1>
      {% endif %}
      <div class="owl-carousel owl-theme">
        {% for book in books %}
        <div class="item d-inline">
          <a href="{% url 'main:detail' book.slug %}" class="text-dark" style="text-decoration: none;">
            <div class="advert-box">
              <img src="{{book.image.url}}" alt="">
              <ul>
                <li>
                  <strong>Nomi:</strong>
                  <span>{{book.title}}</span>
                </li>
                <li>
                  <strong>Avtori:</strong>
                  <span>{{book.author_pen}}</span>
                </li>
                <li>
                  <strong>Janri:</strong>
                  <span>{{book.genre}}</span>
                </li>
              </ul>
              <span class="about-box">{{book.author.address}} <br> {{book.created_at}}</span>
            </div>
          </a>
        </div>
        {% endfor %}
      </div>
    </section>
    <br><br>
  </div>
{% endblock %}


{% block code %}
<script type="text/javascript" src="/static/js/resizer_image.js"></script>
<script>
    let input = document.querySelectorAll('input');
    arr = ['', '', 'Sarlavha', 'Muallif', 'qidiruv']
    for (var i = 0; i < input.length-1; i++) {
        input[i].classList.add('value-input')
        input[i].setAttribute('placeholder', `${arr[i]}`)
        input[i].setAttribute('autocomplete', "off")
    }
    let input_file = document.querySelector('#id_image');
    input_file.style = 'display: none;'
    let target = document.querySelector('#uploadImg')
    let file;

    input_file.addEventListener("change", (event) => {
        event.preventDefault();
        file = event.target.files[0]
        showFile();
    });

    function showFile() {
        let fileType = file.type;
        let validExtensions = ["image/jpeg", "image/jpg", "image/png"];
        if (validExtensions.includes(fileType)) {
            let fileReader = new FileReader();
            fileReader.onload = () => {
                let fileURL = fileReader.result;
                target.attributes.src.nodeValue = `${fileURL}`
            }
            fileReader.readAsDataURL(file);
        } else {
            alert("This is not an Image File!");
        }
    }

    $('#id_image').imageUploadResizer({
        max_width: 360,
        max_height: 810,
        quality: 1,
        do_not_resize: ['gif', 'svg'],
    });
    
  $(".owl-carousel").owlCarousel({
    loop: false,
    margin: 10,
    dots: false,
    nav: false,
  
    responsive: {
      0: {
        items: 2
      },
      768: {
        items: 3
      },
      1336: {
        item: 4
      },
      1340: {
        items: 4
      }
    }
  })
</script>
{% endblock %}